name: Nightly NYC Cool 214 Report

on:
  workflow_dispatch:
    inputs:
      enforce_10pm_et:
        description: "Only send if it is currently 10 PM Eastern?"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

  schedule:
    - cron: "0 2 * * *"
    - cron: "0 3 * * *"

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run report
        env:
          ARCGIS_USERNAME: ${{ secrets.ARCGIS_USERNAME }}
          ARCGIS_PASSWORD: ${{ secrets.ARCGIS_PASSWORD }}

          MS_TENANT_ID: ${{ secrets.MS_TENANT_ID }}
          MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
          MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}

          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}

          ENFORCE_10PM_ET: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.enforce_10pm_et }}
        run: python scripts/send_daily_214_report.py
